sudo: required
service:
  - docker

before_install:
  - docker build -t yuweib/docker-react -f Dockerfile.dev .

script:
  - docker run yuweib/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-732744832743"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id:
    secure: "$AWS_SECRET_KEY"